### PR TITLE
Improve search and group handling and related usability

### PR DESCRIPTION
**Pull request by Wuzzy2**
This PR does the following:

* Add a new button for resetting the search
* Keeps search text after searching (because there's now a dedicated reset button)
* Inserts group name after clicking group item in craft guide
* Use proper tooltips for group buttons in craft guide (e.g. “Any item belonging to the wood group” instead of the item name (which was incorrect IMO))
* Add a few more “defined” groups from Minetest Game (for guaranteed group images)

### CODE REVIEW

**Comment by VanessaE** [comment]
needs rebased

**Comment by Wuzzy2** [comment]
Is this better now?

**Comment by VanessaE** [comment]
Believe it or not, as soon as I merged #62, this one went into conflict again.

**Comment by Wuzzy2** [comment]
OK, I fixed the conflicts.

**Pull request merged**
