### PR TITLE
Add buttons to give oneself items (with 'give' privilege)

### PR DESCRIPTION
**Pull request by Rogier-5**
Hi,
 I created this patch, that adds 'give' buttons to the crafting guide, if the user has 'give' privilege. They provide an easy way to give oneself any items one needs. I'd appreciate if you could consider merging it.

If it needs improvement before it can be merged, please let me know.

### CODE REVIEW

**Comment by VanessaE** [comment]
I'm not sure I see the point of this, since the mod already has Creative inventory support via the "creative" privilege.

**Comment by 0-afflatus** [comment]
I see the point. "creative" ~= "give". If you're not in creative mode that behaviour could be annoying.
:+1: for give button here.

**Comment by Rogier-5** [comment]
That is indeed my reason for proposing this patch. Not everybody who has the give privilege, has, or even wants the creative privilege. The creative privilege permanently affects the behavior of the crafting guide, effectively disabling the lookup of recipes, and changing it to 'give'. It also enables the 'trash inventory' button.Those things are not always desired (and indeed can be annoying): people also like to play in non-creative mode, while they may still have the give privilege for use in exceptional cases. One example user class would be the more privileged users on non-creative servers ('moderator'). It would be nice if U-I supported / facilitated this 'give/non-creative' playing style with 'give' button(s).

**Comment by VanessaE** [comment]
75f719507e42d4329ec67e4ae9dd9e8facea3b25

**Pull request closed without merging**
