### PR TITLE
make listring configurable in creative

### PR DESCRIPTION
**Pull request by DS-Minetest**
screenshot_20170421_192228
Listring to craft, refill and trash is possible.

### CODE REVIEW

**Comment by VanessaE** [comment]
No, definitely not going to merge this - I'm one of those who uses the crafting grid for temp storage even in creative.  Shift-click everything you want to save, then use the trash-all button at the bottom.

**Comment by DS-Minetest** [comment]
Just wait, I'm working on a configurable version of this PR.

**Comment by VanessaE** [comment]
Sounds fair - I would highly recommend you put something on-screen that clearly indicates if shift-click is going to send items to the trash.

**Comment by DS-Minetest** [comment]
Ok, I managed to do something, that works. But it's, well, maybe not a good way.

**Pull request closed without merging**
