### PR TITLE
Bags: Code cleanup and per-bag trash slot.

### PR DESCRIPTION
**Pull request by kaeza**
Small code cleanup, and add a trash slot per bag (#29).

### CODE REVIEW

**Comment by kaeza** [comment]
@ShadowNinja ?

**Comment by ShadowNinja** [comment]
The translations could be updated and the parenthesis around `gsub` are superfluous.
Other than that, looks good.

**Comment by kaeza** [comment]
@ShadowNinja Re: Translation, OK. Re: `gsub`, that's intentional to force the function to discard all extra return values (`gsub` returns the string plus number of replacements made).

**Comment by ShadowNinja** [comment]
:+1:

**Comment by kaeza** [comment]
https://github.com/minetest-mods/irc/commit/d5ad8ffca46752e37a7327356beaebff37b35f73

Thank you!

**Comment by kaeza** [comment]
https://github.com/minetest-technic/unified_inventory/commit/75a0e6a31880bb3b0412288e7add99257805e8d1

**Pull request closed without merging**
