### PR TITLE
Add item_names support for Better "HUD"

### PR DESCRIPTION
**Pull request by MT-Modder**

### CODE REVIEW

**Comment by MT-Modder** [comment]
Bump

**Comment by MT-Modder** [comment]
Bump!

**Comment by VanessaE** [comment]
Although this is just a couple-line change, rather than bumping :-P can you explain just what this is supposed to do?

**Comment by MT-Modder** [comment]
:-P Sure, if the "Better HUD" mod is enabled the hunger and armor huds overlap the item name display. This simply moves the item name display location up a little if that mod is present.

**Comment by VanessaE** [comment]
Ok.  merged, 8bb1c82

**Pull request closed without merging**
