### PR TITLE
Add item_name support for hudbars mod

### PR DESCRIPTION
**Pull request by MT-Modder**
Does the same thing as https://github.com/MT-Modder/unified_inventory/commit/8bb1c8288b45182ed8e1496d1ecc322ed84854a9

### CODE REVIEW

**Comment by MT-Modder** [comment]
Bump.

**Comment by kaeza** [comment]
Can you link to hudbard mod for testing?

**Comment by MT-Modder** [comment]
Forum: https://forum.minetest.net/viewtopic.php?f=9&t=11153
Download: https://forum.minetest.net/download/file.php?id=2735

It fit's it right under the stat bars and right above the item bar...at least for me it did.

**Comment by kaeza** [comment]
bdf9b61779b454e687b81e2dc3df7edc8a52e68b

**Comment by MT-Modder** [comment]
Thanks!

**Pull request closed without merging**
