### PR TITLE
Allow to move back and forth in alternate recipes and usages in craft guide

### PR DESCRIPTION
**Pull request by Wuzzy2**
Allows to move back and forth in alternate recipes and usages in craft guide by adding a “next” and “previous” button which replace the old “Alternate” button.

Translation strings and German strings are updated as well.

### CODE REVIEW

**Comment by HybridDog** [comment]
Could  you also add buttons to jump to the recipes of the next/previous mod, it takes a lot time to click away that myriad stairsplus recipes.

**Comment by Wuzzy2** [comment]
No.

**Comment by VanessaE** [comment]
Already needs a rebase :smile:

**Comment by Wuzzy2** [comment]
Hopefully I did everything right. Rebase done. I hope so.

**Pull request merged**
